### ISSUE TITLE
Which license does apply to this work?

### ISSUE THREAD

**Issue by ifraixedes** [govolution/avet#1]
First of all, thanks to release this work on a public repository.

Nonetheless, this repo doesn't have any concrete license (or it isn't easy to see), so I would like that you consider to choose one to avoid the confusion that it causes with its absence, the work has applied the default copyright laws which the most of the people we aren't sure the implications because we aren't lawyers.

[This page may help you to decide which one is more convenient for you and all the benefits that an open license has over a closed one](https://help.github.com/articles/open-source-licensing/), however, don't get me wrong, choose the one that fits better to your specific case, independently if it's open or not.

Thanks for considering.

**Comment by govolution** [comment]
Good point, thank you for pointing out. I added the LICENSE file and some comments.
