### ISSUE TITLE
No Window option for executable

### ISSUE THREAD

**Issue by easy4MEr** [govolution/avet#11]
Hi, 
first of all I would like to thank you for awesome work! 

Is there any option to compile the final binary in "no window" mode? I've tried multiple ways how to achieve that, but with no success. Everytime I launch created binary, I can see application window hanging in the system....

Tested on Windows 7, Windows 8.1, Windows 10

![image](https://user-images.githubusercontent.com/24946510/28576888-729c39bc-7155-11e7-824a-dc3ce90cab72.png)

Thank you for response.

**Comment by govolution** [comment]
Thanks! Honestly I don't know if that is possible, but maybe it should, never needed it. I close since it not an issue and it goes to my feature request list.
