### ISSUE TITLE
Example 1 picked up by Avast

### ISSUE THREAD

**Issue by HadManySons** [govolution/avet#14]
Using latest version of Avast (as of 20171213), Avast immediately caught it as Win64:Malware-gen. Detected by the File Shield module

Payload was build using the instruction included in Example 1 of the README

**Comment by govolution** [comment]
thx
- you can try to strip the .exe file
- or another technique

**Comment by govolution** [comment]
Closed, no more feedback. Maybe in future I put strip into all scripts and change docs.
