### ISSUE TITLE
File "./avet_fabric.py", line 75, in <module>

### ISSUE THREAD

**Issue by gearcapitan** [govolution/avet#15]
![kali linux-2018-01-08-15-46-47](https://user-images.githubusercontent.com/13740942/34694007-3070ac26-f48b-11e7-84df-650c38575029.png)
what ?

![kali linux-2018-01-08-16-03-18](https://user-images.githubusercontent.com/13740942/34694648-7bf398fa-f48d-11e7-8d83-3d9036585714.png)

**Comment by govolution** [comment]
![auswahl_040](https://user-images.githubusercontent.com/6421894/34783080-72ab5512-f622-11e7-891a-0c56918b2a6d.png)

Can not reproduce. Please ensure you use Kali 2 and match all requirements described in the README.md file.

**Comment by govolution** [comment]
Closed, no feedback.
