### ISSUE TITLE
All the backdoors are now getting detected by windows defender ? How to solve this issue ?

### ISSUE THREAD

**Issue by ghost** [govolution/avet#17]

**Comment by govolution** [comment]
Just tested with ./build/build_win32_meterpreter_rev_https_50xshikata.sh and was not detected, windows 7.

**Comment by ghost** [comment]
Tested the same template on W10 and DETECTED.

**Comment by govolution** [comment]
./build/build_win32_meterpreter_rev_https_shikata_loadfile.sh
-> worked for me on Windows 10 with defender.

**Comment by evaexe** [comment]
you'r windows defend are updated ?
 for me ./build/build_win32_meterpreter_rev_https_shikata_loadfile.sh is detected.

**Comment by ghost** [comment]
You'r windows defender are update ? 
Beacause for me ./build/build_win32_meterpreter_rev_https_shikata_loadfile.sh is detected.

Whatever, Can you send all commande what you does for the loadfile build ?

Thanks !!

**Comment by govolution** [comment]
Of course defender is updated. I never had similar problems.
It is all in ./build/build_win32_meterpreter_rev_https_shikata_loadfile.sh, you only need to edit it with your correct ip.

**Comment by ghost** [comment]
Hi,
Yes the  ./build/build_win32_meterpreter_rev_https_shikata_loadfile.sh is not detected,
But it don't work. 
he don't try to connect to the attack machine.

they is a difference between the code and the exemple at line 13 
./make_avet -l thepayload.exe -E

**Comment by govolution** [comment]
I will update the readme soon for the next version. The build script works for me. If a connection does not work it may have several reasons and unfortunetely I can not give support for everything.
