### ISSUE TITLE
Unable to run ./format.sh command

### ISSUE THREAD

**Issue by mgraf2** [govolution/avet#2]
I created the sh.txt file using msfvenom, but when I run the ./format.sh script I get the following error:

![image](https://cloud.githubusercontent.com/assets/24736547/23139048/2fe7a05c-f770-11e6-89cc-fc69b942d7b9.png)

I used Kali 2.0 and installed tdm-gcc per instructions.

Thanks,

**Comment by govolution** [comment]
Maybe you use 32bit kali? Try to compile sh_format.c with:
gcc -o sh_format sh_format.c
For the next step you need further to compile make_avet again:
gcc -o make_avet make_avet.c

**Comment by mgraf2** [comment]
I was using 32bit kali, I did recompile both, and worked thanks!
