### ISSUE TITLE
Payload not working

### ISSUE THREAD

**Issue by misterch0c** [govolution/avet#24]
Hello,

I've been trying your tools and I kept it simple, using default options.
It seems that most payload are not running (Windows 7) except for the bind ones that seems to be fine.

![image](https://user-images.githubusercontent.com/8876235/54816060-9da12d00-4c93-11e9-9263-74953b7f6437.png)

**Comment by govolution** [comment]
Works on my machine.
![2019-03-22 20_30_48-kali-linux-2017 3-vm-amd64 - VMware Workstation](https://user-images.githubusercontent.com/6421894/54848458-96087500-4ce1-11e9-81a6-fbc08b61ba73.png)

**Comment by govolution** [comment]
Note: Read through the build script you are using, some require a webserver running for dropping the payload.
