### ISSUE TITLE
Ran avet -f with meterpreter reverse tcp payload

### ISSUE THREAD

**Issue by mgraf2** [govolution/avet#3]
I created a new executable with AVET and meterpreter reverse TCP payload and while AVG scans the file and finds nothing, as soon as I execute the file AVG catches it (I believe it is scanning it in memory).
Which AVs did you test this against?

**Comment by mgraf2** [comment]
I think it might be a Signature Match Coincidence...

![image](https://cloud.githubusercontent.com/assets/24736547/23141528/d7d3c672-f77c-11e6-99d8-6f7a3ec6952e.png)

**Comment by govolution** [comment]
Have you tried:
$ ./make_avet -f sh_clean.txt
$ wine gcc.exe -m32 -o mytrojan.exe avet.c
