### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by enkeyz** [govolution/avet#6]
So I used that bash script from Example 1, compiled it with mingw, and when I open exe on my VM, I get appcrash.
![virtualbox_win7_x86_02_06_2017_14_37_09](https://cloud.githubusercontent.com/assets/17646853/26725904/ff1b8e12-47a0-11e7-8def-7277751e87f5.png)

**Comment by govolution** [comment]
Did you compile it as described here?
https://govolution.wordpress.com/2017/02/04/using-tdm-gcc-with-kali-2/

**Comment by enkeyz** [comment]
Looks like not:D Will report back, if it works!

**Comment by govolution** [comment]
OK. I always had problems like that when using different compilers, don't know why. If any problems let me know.

**Comment by enkeyz** [comment]
So, now exe is running fine, but metasploit is stuck at here:
![screenshot_20170602_151532](https://cloud.githubusercontent.com/assets/17646853/26727262/72d74c6a-47a6-11e7-89b7-d82ea5ee07b4.png)

I'm not running any AVs, and firewall is off. It's a clean virtual machine.

**Comment by govolution** [comment]
OK, looks like a msf problem or config problem. Send the shellscript you used (with your settings included) and I have a look.

**Comment by govolution** [comment]
Also might be a network problem... VirtualBox sometimes sucks at this.

**Comment by enkeyz** [comment]
Network is fine. I tried with a simple msfvenom payload.

Script: https://pastebin.com/D4F3gbS3

Edit: rebooted my VMs, still same problem.

**Comment by govolution** [comment]
Your handler is tcp, but the payload is https, so:
set payload windows/meterpreter/reverse_https
on msfconsole.

**Comment by enkeyz** [comment]
LOL man! Did I really missed that? :D Thanks:)

Bye the way, thanks for your work, it's fully undetectable by AVs - 0/61 - really nice work!

**Comment by govolution** [comment]
No problem ;).

**Comment by enkeyz** [comment]
I tried Veil Framework and Shellter before, but they get caught immediately. I'm not really into these things, but why are your project works, and others not?

**Comment by govolution** [comment]
Hard to say without a closer look. Might be my tool is newer and is not recognized because of that. Or maybe the evasion techniques that are used are effective. If you want to know more check out:
https://deepsec.net/docs/Slides/2014/Why_Antivirus_Fails_-_Daniel_Sauder.pdf
https://govolutionde.files.wordpress.com/2014/05/avevasion_pentestmag.pdf
