### ISSUE TITLE
Where are the files saved?

### ISSUE THREAD

**Issue by gearcapitan** [govolution/avet#7]
![kali linux-2017-06-07-01-26-00](https://user-images.githubusercontent.com/13740942/26864985-48714c8c-4b20-11e7-9110-365c74816358.png)

There is nothing in the avet folder !!!!!!

**Comment by govolution** [comment]
A more exact description may help !!!!!! 
But anyway, guessing is also fun, so you may execute one of the build scripts, eg.:
./build/build_win32_meterpreter_rev_https_fopen_shikata.sh
from the avet directory and send the output.

**Comment by gearcapitan** [comment]
where saved exe files?

**Comment by govolution** [comment]
In the avet folder, as said in the script. If you want further help please take the steps I explained before.
